### ISSUE TITLE
[Feature Request] modifiers + backspace / delete

### ISSUE THREAD

**Issue by Letsric** [pop-os/cosmic-edit#226] opened 2024-08-12 12:18 UTC
This is similar to #157.

In other editors, holding Ctrl and pressing backspace deletes an entire word. Ctrl + delete does the same thing, but deletes the word to the right of the cursor. It would be nice for cosmic-edit to follow this behavior.

**Comment by leviport** [comment] 2024-08-14 19:04
Duplicate of https://github.com/pop-os/cosmic-edit/issues/208

**Closed by leviport** 2024-08-14 19:04 UTC
