### ISSUE TITLE
[INCONSISTENCY] COSMIC text doesn't zoom with ctrl + plus; while COSMIC terminal does.

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-edit#279] opened 2024-12-16 21:26 UTC
In Cosmic Terminal, I can Ctrl + plus to zoom in and make the text bigger, I expected this functionality as well in Cosmic Text editor.

With regards,

Feike

**Comment by leviport** [comment] 2024-12-16 21:31
Duplicate of https://github.com/pop-os/cosmic-edit/issues/277

**Closed by leviport** 2024-12-16 21:31 UTC
