### ISSUE TITLE
IME is not support

### ISSUE THREAD

**Issue by deviswu** [pop-os/cosmic-edit#227] opened 2024-08-15 08:19 UTC
when will it support IME？I can not use chinese input method!

**Comment by mmstick** [comment] 2024-08-15 08:26
Upstream issue: https://github.com/iced-rs/iced/issues/979

**Comment by deviswu** [comment] 2024-08-16 02:14
is there an example  i can use？ thank you

**Comment by mmstick** [comment] 2024-08-22 11:23
Duplicate of https://github.com/pop-os/libcosmic/issues/578

**Closed by mmstick** 2024-08-22 11:23 UTC
